version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*" # Groups all updates into one PR