@startuml
skinparam componentStyle rectangle

actor "Client" as Client

cloud "External Payment Provider" as EPP <<External Service>>

package "System Architecture" {

    component "1. Presentation Layer" as Presentation {
        [AIM Middleware] as AuthFilter
        [REST API Controllers] as API
    }

    component "2. Application Layer" as AppLayer {
        [Application Services] as Services
    }

    component "3. Domain Layer (DDD)" as DomainLayer {
        [Domain Model] as Domain
    }

    component "4. Infrastructure Layer" as InfraLayer {
        [Database Repository] as Repo
        [OS File Adapter] as OSAdapter
        [Payment API Client] as PaymentClient
    }
}

database "Relational Database" as DB
node "Server Operating System" as OS {
    [File System Utilities] as OSFS
}


Client .down.> AuthFilter : HTTP Requests
AuthFilter .down.> API : Validates Token
API .down.> Services : DTOs

Services .down.> Domain : Applies Business Rules
Services .down.> Repo : Requests Data
Services .down.> OSAdapter : Requests File Ops
Services .down.> PaymentClient : Init Payment

Repo .down.> DB : SQL
OSAdapter .down.> OSFS : uses
PaymentClient .right.> EPP: API Call

@enduml